import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const { to, itinerary } = await request.json();

    if (!to || !itinerary) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    // Format itinerary as HTML email
    let html = `
      <!DOCTYPE html>
      <html>
      <head><meta charset="utf-8"></head>
      <body style="font-family: -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #2563eb;">Your Travel Itinerary</h1>
        <div style="background: linear-gradient(135deg, #3b82f6, #6366f1); color: white; padding: 24px; border-radius: 12px; margin: 16px 0;">
          <h2 style="margin: 0;">${itinerary.destination}</h2>
          <p style="opacity: 0.9; margin: 8px 0 0;">${itinerary.travelers} traveler(s) · ${itinerary.days} days</p>
        </div>
        <p>${itinerary.overview}</p>
    `;

    if (itinerary.dayPlans) {
      itinerary.dayPlans.forEach((day: any) => {
        html += `
          <div style="background: #f8fafc; border-radius: 12px; padding: 16px; margin: 12px 0;">
            <h3 style="color: #1e293b; margin: 0 0 8px;">Day ${day.day}: ${day.title}</h3>
            <p style="color: #64748b; margin: 0 0 12px;">${day.description}</p>
        `;
        if (day.activities) {
          day.activities.forEach((a: any) => {
            html += `<div style="padding: 8px 0; border-bottom: 1px solid #e2e8f0;">
              <strong>${a.time}</strong> — ${a.name}
              <p style="margin: 4px 0 0; color: #64748b; font-size: 14px;">${a.description}</p>
            </div>`;
          });
        }
        if (day.transportTips) {
          html += `<p style="font-size: 14px; color: #0284c7; margin: 12px 0 0;">🚇 ${day.transportTips}</p>`;
        }
        html += `</div>`;
      });
    }

    if (itinerary.tips?.length) {
      html += `<h3>💡 Travel Tips</h3><ul>`;
      itinerary.tips.forEach((tip: string) => {
        html += `<li style="margin: 8px 0; color: #64748b;">${tip}</li>`;
      });
      html += `</ul>`;
    }

    html += `
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;">
        <p style="color: #94a3b8; font-size: 12px;">Generated by Travel Planner · AI-powered trip planning for China</p>
      </body>
      </html>
    `;

    // Send email via QQ SMTP
    const transporter = nodemailer.createTransport({
      host: "smtp.qq.com",
      port: 587,
      secure: false,
      auth: {
        user: process.env.EMAIL_USER || "330261196@qq.com",
        pass: process.env.EMAIL_PASS || "nqogzxfppzjscaaj",
      },
    });

    await transporter.sendMail({
      from: `"Travel Planner" <${process.env.EMAIL_USER || "330261196@qq.com"}>`,
      to: to,
      subject: `Your ${itinerary.destination} Itinerary — Travel Planner`,
      html: html,
    });

    return NextResponse.json({ success: true });
  } catch (error: any) {
    console.error("Email send failed:", error);
    return NextResponse.json(
      { error: error.message || "Failed to send email" },
      { status: 500 }
    );
  }
}
